# **Theoretical Questions:**

# **1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**


**Purpose of NumPy in Scientific Computing and Data Analysis**

NumPy (short for Numerical Python) is a core library in Python for numerical computations. It provides high-performance tools to work with large, multi-dimensional arrays and matrices, along with a vast collection of mathematical functions to operate on these arrays. NumPy serves as the backbone for many scientific libraries in Python, such as Pandas, SciPy, TensorFlow, and Scikit-learn.

**Advantages of NumPy**

**1. Efficient Numerical Operations:**

NumPy arrays (ndarrays) are optimized for performance, enabling fast element-wise computations.
Operations on NumPy arrays are implemented in C, avoiding the slower Python loops.

**2. Multi-dimensional Arrays:**

Supports arrays of arbitrary dimensions (1D, 2D, 3D, etc.).
Offers specialized operations for reshaping, slicing, and performing matrix computations.

**3. Broadcasting:**

NumPy automatically applies operations element-wise across arrays of compatible shapes, removing the need for explicit looping.

**4. Vectorized Operations:**

Many mathematical operations can be performed directly on arrays, making code concise and faster compared to Python lists.

**5. Rich Mathematical Functions:**

Includes functions for linear algebra, Fourier transforms, random number generation, and basic statistics.
Ideal for solving problems in machine learning, physics, engineering, and finance.

**6. Memory Efficiency:**

NumPy arrays consume less memory compared to Python lists for storing the same data because they use contiguous memory blocks.
Arrays are homogenous (all elements must be of the same data type), which contributes to their efficiency.

**7. Interoperability:**

Works well with other scientific libraries like Pandas, Matplotlib, and Scikit-learn.
Provides easy integration with low-level languages such as C and Fortran.

**8. Ease of Use:**

Its syntax is simple and intuitive for numerical operations, reducing development time.

**9. Handling Large Datasets:**

NumPy efficiently processes large datasets, making it suitable for big data applications.

How NumPy Enhances Python's Capabilities for Numerical Operations

**1. Faster Performance:**

NumPy arrays are much faster than Python lists for numerical operations due to their implementation in C and their contiguous memory layout.

**Example:**

In [ ]:
import numpy as np
import time

# Create a large list and NumPy array
python_list = list(range(1, 1000000))
numpy_array = np.array(range(1, 1000000))

# Time taken for Python list sum
start = time.time()
sum(python_list)
print("Python list time:", time.time() - start)

# Time taken for NumPy array sum
start = time.time()
np.sum(numpy_array)
print("NumPy array time:", time.time() - start)


Python list time: 0.00910186767578125
NumPy array time: 0.002977132797241211


**2. Vectorized Operations:**

NumPy eliminates the need for slow Python loops by applying vectorized operations directly on arrays.

**Example:**

In [ ]:
# Element-wise addition using NumPy
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2  # [5, 7, 9]


In [ ]:
result = [x + y for x, y in zip([1, 2, 3], [4, 5, 6])]
result

[5, 7, 9]

**3. Advanced Indexing and Slicing:**

NumPy simplifies data manipulation using powerful slicing and indexing capabilities, which are more advanced than Python lists.

**Example:**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])  # Output: [2 3 4]


[2 3 4]


**4. Extensive Math Functions:**

Built-in support for mathematical operations like dot products, matrix multiplications, and statistical calculations, which are tedious to implement manually.

**5. Support for Multi-dimensional Data:**

While Python lists are limited to 1D or nested structures, NumPy arrays easily handle multi-dimensional data (e.g., 2D matrices, 3D tensors).

**Example:**

In [ ]:
# Create a 2D array
matrix = np.array([[1, 2], [3, 4]])
print(matrix.T)  # Transpose


[[1 3]
 [2 4]]


# **2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?**

**Comparison of np.mean() and np.average()**

Both np.mean() and np.average() are used to calculate the average of a NumPy array, but there are key differences in their functionality and use cases:

**1. np.mean()**

**Purpose:** Calculates the arithmetic mean (average) of the array elements.

**Weights:** Does not support weights. It simply divides the sum of elements by the total number of elements.

**Syntax:**

np.mean(array, axis=None, dtype=None, keepdims=False)

**Parameters:**

**axis:** Specifies the axis along which to calculate the mean.

**dtype:** Specifies the data type for the calculation.

**keepdims:** Retains the dimensions of the original array if set to True.

**Example:**

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # Output: 3.0


3.0


**2. np.average()**

**Purpose:** Computes the weighted average of the array elements. If no weights are provided, it behaves like np.mean().

Weights: Supports weights, making it useful for cases where some elements contribute more to the average than others.

**Syntax:**

np.average(array, axis=None, weights=None, returned=False)

**Parameters:**

**axis:** Specifies the axis along which to calculate the average.

**weights:** A sequence of weights for computing the weighted average. Must have the same shape as the input array.

**returned:** If True, returns a tuple containing the average and the sum of the weights.

**Example:**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 1, 2, 2, 4])
print(np.average(arr, weights=weights))  # Output: 4.0


3.7


**When to Use np.mean()**

When all data points have equal importance or weight.
For simple statistical calculations without any weighted contributions.

**Example**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(np.mean(arr))  # Output: 30.0


30.0


**When to Use np.average()**

When different elements have different levels of importance (weights).
Useful in scenarios such as:
Calculating a student's final grade based on weighted scores.
Calculating portfolio returns with weights assigned to each stock.

**Example:**

In [ ]:
grades = np.array([80, 90, 70])
weights = np.array([0.3, 0.5, 0.2])  # Weightage of assignments
print(np.average(grades, weights=weights))  # Output: 82.0


83.0


# **3. Describe the methods for reversing a NumPy array along different axes.Provide examples for 1D and 2D arrays.**


Reversing a NumPy array involves changing the order of elements along a specific axis. Here are the methods to reverse a NumPy array for 1D and 2D arrays:


**1. Reversing a 1D NumPy Array**

You can reverse a 1D array by using slicing or the np.flip() function.

**Method 1: Using Slicing**

In [ ]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_1d = arr_1d[::-1]

print("Original 1D Array:", arr_1d)
print("Reversed 1D Array:", reversed_1d)


**Method 2: Using np.flip()**

In [ ]:
# Reverse using np.flip
reversed_1d_flip = np.flip(arr_1d)

print("Reversed 1D Array with np.flip:", reversed_1d_flip)


**2. Reversing a 2D NumPy Array**

For 2D arrays, you can reverse elements along different axes (rows, columns, or both).

**Method 1: Reverse All Elements (Flattened Order)**

**Using slicing:**

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse all elements
reversed_2d = arr_2d[::-1, ::-1]

print("Original 2D Array:")
print(arr_2d)
print("Fully Reversed 2D Array:")
print(reversed_2d)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Fully Reversed 2D Array:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


**Method 2: Reverse Rows**

Reverse the order of rows (axis 0) while keeping the columns intact.

In [ ]:
# Reverse rows
rows_reversed = arr_2d[::-1, :]

print("Rows Reversed:")
print(rows_reversed)


Rows Reversed:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


**Method 3: Reverse Columns**

Reverse the order of columns (axis 1) while keeping the rows intact.

In [ ]:
# Reverse columns
columns_reversed = arr_2d[:, ::-1]

print("Columns Reversed:")
print(columns_reversed)


Columns Reversed:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


**Method 4: Using np.flip()**

You can reverse along specific axes using the np.flip() function:

**Reverse along rows:**

In [ ]:
rows_flipped = np.flip(arr_2d, axis=0)
print("Rows Flipped with np.flip:")
print(rows_flipped)


Rows Flipped with np.flip:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
columns_flipped = np.flip(arr_2d, axis=1)
print("Columns Flipped with np.flip:")
print(columns_flipped)


Columns Flipped with np.flip:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
both_axes_flipped = np.flip(arr_2d)
print("Flipped along Both Axes:")
print(both_axes_flipped)


Flipped along Both Axes:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


# **4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.**


**Determining the Data Type of Elements in a NumPy Array**

You can determine the data type of elements in a NumPy array using the following methods:

**1. Using .dtype Attribute**

The .dtype attribute returns the data type of the elements in the array.

In [ ]:
import numpy as np

# Example array
arr = np.array([1, 2, 3])

# Check data type
print("Data type:", arr.dtype)


Data type: int64


**2. Using type() Function**

The type() function returns the type of the array object itself, which is often a subclass of numpy.ndarray, but it does not give the data type of the elements.

In [ ]:
# Example
print("Array type:", type(arr))  # Outputs: <class 'numpy.ndarray'>


Array type: <class 'numpy.ndarray'>


Importance of Data Types in NumPy

Data types in NumPy arrays play a crucial role in memory management and performance. Here's why:

**1. Memory Efficiency**

**Fixed Data Types:** NumPy arrays store data in contiguous blocks of memory with a fixed data type. For example, int32 takes 4 bytes per element, while float64 takes 8 bytes. This is more efficient than Python lists, where each element is an object, consuming more memory.

**Customizable Data Types:** You can choose the appropriate data type (e.g., int8, int16, float32) based on your needs, minimizing memory usage.

**Example:**

In [ ]:
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
arr_int64 = np.array([1, 2, 3], dtype=np.int64)

print("Memory used by int32:", arr_int32.nbytes, "bytes")
print("Memory used by int64:", arr_int64.nbytes, "bytes")


Memory used by int32: 12 bytes
Memory used by int64: 24 bytes


**2. Computational Performance**

**Homogeneous Data:** NumPy arrays are homogeneous, meaning all elements have the same data type. This allows NumPy to use highly optimized C-based operations, leading to faster computations compared to Python lists.

**Vectorized Operations:** NumPy can perform operations directly on arrays without explicit loops, leveraging low-level optimizations tied to the data type.

**Example:**

In [ ]:
# NumPy vs. Python list performance
arr = np.arange(1_000_000, dtype=np.float32)
py_list = list(range(1_000_000))

%timeit arr * 2  # Fast NumPy operation
%timeit [x * 2 for x in py_list]  # Slower Python list operation


334 µs ± 14.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
95.3 ms ± 19.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


**3. Accuracy and Precision**

**Choosing the Right Precision:** When dealing with numerical computations, the data type affects precision. For example, float32 is less precise than float64, which can lead to rounding errors in large calculations.

**Example:**

In [ ]:
arr_float32 = np.array([0.1, 0.2, 0.3], dtype=np.float32)
arr_float64 = np.array([0.1, 0.2, 0.3], dtype=np.float64)

print("Sum with float32:", arr_float32.sum())  # May have rounding errors
print("Sum with float64:", arr_float64.sum())  # More accurate


Sum with float32: 0.6
Sum with float64: 0.6000000000000001


**4. Compatibility with External Libraries**

Many scientific and machine learning libraries (e.g., Pandas, TensorFlow) require specific data types for input. Using the wrong data type can cause errors or inefficiencies.

**Example:**

TensorFlow models typically require data in float32 for training to optimize GPU memory usage and speed.

# **5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

**Definition of ndarray in NumPy:**

An ndarray (n-dimensional array) in NumPy is a powerful data structure used to store and manipulate multidimensional data efficiently. It is the core component of the NumPy library and allows for fast mathematical and logical operations on large datasets.

**Key Features of ndarray:**

**1. Multidimensional:**

An ndarray can represent data in multiple dimensions (1D, 2D, 3D, etc.).
Example:
1D array: [1, 2, 3]
2D array: [[1, 2], [3, 4]]
3D array: A stack of 2D matrices.

**2. Homogeneous Data:**

All elements in an ndarray must have the same data type (e.g., integers, floats).
This uniformity ensures efficient memory usage and faster operations.

**3. Efficient Memory Usage:**

ndarray uses a contiguous block of memory, unlike Python lists, which store pointers to objects. This allows for faster computations.

**4. Vectorized Operations:**

Arithmetic operations can be performed directly on arrays without the need for explicit loops.

**Example:**



In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Output: [5 7 9]


[5 7 9]


**5. Broadcasting:**

NumPy arrays can perform operations on arrays of different shapes by "stretching" smaller arrays.

**Example:**

In [2]:
a = np.array([1, 2, 3])
b = 2
print(a * b)  # Output: [2 4 6]


[2 4 6]


**6. Indexing and Slicing:**

Supports advanced indexing, slicing, and subsetting of data.

**Example:**

In [3]:
a = np.array([[1, 2], [3, 4]])
print(a[0, 1])  # Output: 2
print(a[:, 0])  # Output: [1 3]


2
[1 3]


**7. Rich Functionality:**

Includes many built-in methods for statistical, mathematical, and linear algebra operations (e.g., mean(), sum(), dot()).

**8. Shape and Reshaping:**

ndarray provides attributes like .shape, .ndim, and .size to understand its structure and allows reshaping without data loss.

**Example:**

In [4]:
a = np.array([1, 2, 3, 4])
print(a.reshape(2, 2))  # Output: [[1 2]
                         #          [3 4]]


[[1 2]
 [3 4]]


### **Differences Between `ndarray` and Python Lists**

| Feature               | ndarray (NumPy)                                     | Python List                                  |
|-----------------------|----------------------------------------------------|---------------------------------------------|
| **Homogeneity**       | All elements must have the same data type.          | Can store elements of different data types. |
| **Speed**             | Faster due to optimized C-based implementation.     | Slower due to Python’s dynamic typing.      |
| **Memory Efficiency** | Uses less memory (stores data in contiguous blocks).| Requires more memory (stores pointers to objects). |
| **Operations**        | Supports vectorized and broadcasting operations.    | Requires explicit loops for element-wise operations. |
| **Multidimensional Data** | Supports multidimensional arrays natively (e.g., 2D, 3D). | Requires nested lists for multidimensional data. |
| **Built-in Methods**  | Provides a wide range of mathematical and statistical functions. | Limited built-in support for numerical operations. |
| **Data Reshaping**    | Can easily reshape arrays.                          | Not applicable for lists.                   |


**Example: Performance Comparison**

Addition using NumPy vs Python List:

In [5]:
import numpy as np
import time

# NumPy ndarray
a = np.array([i for i in range(1000000)])
b = np.array([i for i in range(1000000)])
start = time.time()
c = a + b
print("NumPy Time:", time.time() - start)

# Python List
a_list = [i for i in range(1000000)]
b_list = [i for i in range(1000000)]
start = time.time()
c_list = [a_list[i] + b_list[i] for i in range(len(a_list))]
print("Python List Time:", time.time() - start)


NumPy Time: 0.0026268959045410156
Python List Time: 0.2096569538116455


# **6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

**Performance Benefits of NumPy Arrays over Python Lists**

NumPy arrays (ndarray) are specifically designed for high-performance numerical computations, making them significantly faster and more efficient than Python lists for large-scale numerical operations. Below is a detailed analysis of the benefits:

### **Performance Benefits of NumPy Arrays over Python Lists**

| **Feature**                | **NumPy Arrays**                                                                 | **Python Lists**                                                |
|----------------------------|---------------------------------------------------------------------------------|----------------------------------------------------------------|
| **1. Speed**               | - NumPy arrays are implemented in C, allowing direct memory access. <br> - Much faster for numerical operations (e.g., addition, multiplication). | - Python lists are slower because they rely on interpreted Python code for operations. <br> - Element-wise operations require explicit loops. |
| **2. Memory Efficiency**   | - NumPy stores data in contiguous memory blocks, requiring less memory. <br> - Fixed data types reduce overhead. | - Lists store pointers to objects, resulting in higher memory usage. <br> - Each element is a full-fledged Python object. |
| **3. Vectorized Operations** | - Supports **vectorized operations** (e.g., addition, subtraction) without loops. <br> - Operates on entire arrays at once. | - Operations require explicit loops, which are slower and less efficient. |
| **4. Broadcasting**        | - Allows operations between arrays of different shapes by "broadcasting" values. <br> - Simplifies operations like matrix addition/multiplication. | - No native support for broadcasting; requires manual logic. |
| **5. Built-in Functions**  | - Comes with optimized mathematical, statistical, and linear algebra functions. <br> - Functions are faster because they are implemented in low-level C code. | - Python lists have limited built-in support for numerical functions. <br> - Additional libraries (e.g., `math`) are needed, which are slower. |
| **6. Multidimensional Data** | - Handles multidimensional arrays (2D, 3D) natively. <br> - Easy reshaping, slicing, and advanced indexing. | - Multidimensional data requires nested lists, which are cumbersome and error-prone. |
| **7. Parallelism**         | - Utilizes efficient parallel processing for large computations. <br> - Many NumPy functions are multi-threaded. | - Python lists do not natively support parallelism in computations. |

**Example: Performance Comparison**

**1. Speed Comparison**

In [6]:
import numpy as np
import time

# Large dataset size
n = 10**6

# NumPy array
array = np.arange(n)

# Python list
py_list = list(range(n))

# NumPy addition
start = time.time()
array_result = array + 5
end = time.time()
print(f"NumPy time: {end - start:.5f} seconds")

# Python list addition
start = time.time()
list_result = [x + 5 for x in py_list]
end = time.time()
print(f"Python list time: {end - start:.5f} seconds")


NumPy time: 0.01666 seconds
Python list time: 0.18563 seconds


**2. Memory Efficiency**

In [7]:
import numpy as np
import sys

# NumPy array
array = np.arange(10**6)
print(f"NumPy array size: {array.nbytes} bytes")

# Python list
py_list = list(range(10**6))
print(f"Python list size: {sys.getsizeof(py_list) + sys.getsizeof(py_list[0]) * len(py_list)} bytes")


NumPy array size: 8000000 bytes
Python list size: 32000056 bytes


# **7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.**

| Feature         | `vstack()`                                     | `hstack()`                                     |
|------------------|-----------------------------------------------|-----------------------------------------------|
| **Purpose**      | Stacks arrays vertically (row-wise).          | Stacks arrays horizontally (column-wise).     |
| **Input Shapes** | Arrays must have the same number of columns.  | Arrays must have the same number of rows.     |
| **Output Shape** | Adds rows to create a taller array.           | Adds columns to create a wider array.         |

### **Examples**

#### Example 1: Using `vstack()`




In [8]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


Example 2: Using hstack()

In [9]:
import numpy as np

a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

result = np.hstack((a, b))
print(result)


[[1 4]
 [2 5]
 [3 6]]


# **8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions**

| Feature            | `fliplr()`                                   | `flipud()`                                   |
|--------------------|---------------------------------------------|---------------------------------------------|
| **Purpose**        | Flips the array left to right (horizontally). | Flips the array upside down (vertically).    |
| **Axis Affected**  | Affects the columns of the array.           | Affects the rows of the array.               |
| **Effect on Shape**| Does not change the shape of the array.     | Does not change the shape of the array.      |
| **Usage**          | Commonly used for 2D arrays (matrices) to reverse columns. | Commonly used for 2D arrays (matrices) to reverse rows. |

### **Examples**

#### Example 1: Using `fliplr()`



In [10]:

import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

result = np.fliplr(a)
print(result)

[[3 2 1]
 [6 5 4]]


Example 2: Using flipud()

In [11]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

result = np.flipud(a)
print(result)


[[4 5 6]
 [1 2 3]]


# **9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

| Feature             | `array_split()`                                      |
|---------------------|------------------------------------------------------|
| **Purpose**         | Splits an array into multiple sub-arrays.            |
| **Functionality**   | It allows splitting an array into any number of sub-arrays along a specified axis. |
| **Uneven Splits**   | When the array cannot be evenly split, the method distributes the remaining elements across the sub-arrays. Some sub-arrays may contain one extra element to ensure all elements are included. |
| **Input Parameters**| Takes the array to split, the number of splits (or an array of indices), and an optional axis. |
| **Returns**         | A list of sub-arrays. Each sub-array is a view on the original array. |

### **Example**


In [12]:


import numpy as np

# Creating a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Splitting the array into 4 parts
result = np.array_split(a, 4)

print(result)


[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


**Handling Uneven Splits:**

If an array cannot be evenly divided, array_split() ensures that all elements are included, with the extra elements distributed across the resulting sub-arrays.

# **10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

### **Vectorization in NumPy**

| Feature                 | Vectorization in NumPy                              |
|-------------------------|-----------------------------------------------------|
| **Definition**           | Vectorization refers to the process of performing element-wise operations on entire arrays without the need for explicit loops. |
| **Purpose**              | It allows operations to be applied to whole arrays or matrices efficiently, leveraging low-level optimizations. |
| **How it Works**         | Instead of using Python loops to iterate over array elements, NumPy applies the operation directly to the entire array or specific slices. |
| **Benefits**             | Faster execution, more concise code, and better memory efficiency. |
| **Example**              | Instead of looping over an array to add 5 to each element, vectorization lets you do `a + 5` directly on the array. |



In [13]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = a + 5  # Vectorized operation
print(b)


[6 7 8 9]


In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4])

# Broadcasting 'b' to match the shape of 'a'
result = a + b
print(result)


[5 6 7]


**How Vectorization and Broadcasting Contribute to Efficient Array Operations**

**1. Vectorization:**

Eliminates the need for explicit loops, making the code cleaner and faster.
Operations on entire arrays are optimized internally, leading to significant performance improvements, especially with large datasets.

**2. Broadcasting:**

Enables operations between arrays of different shapes without needing to replicate data manually, saving memory and computational overhead.
It automatically adjusts the smaller array's shape to fit the larger one, allowing for element-wise operations to occur seamlessly across different dimensions.
Together, vectorization and broadcasting make NumPy highly efficient for numerical computations, as they reduce the amount of code, memory usage, and computational time while maximizing performance.

# **Practical Questions:**

# **1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns**

In [ ]:
import random
import numpy as np
arr = np.random.randint(1,100,(3,3))
arr

array([[91,  9, 85],
       [58, 86, 33],
       [ 3, 91, 25]])

# **2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

In [ ]:
import numpy as np

# Step 1: Generate a 1D array with 10 elements
array_1d = np.arange(10)

# Step 2: Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Step 3: Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

print("1D array with 10 elements:")
print(array_1d)
print("\nReshaped into a 2x5 array:")
print(array_2x5)
print("\nReshaped into a 5x2 array:")
print(array_5x2)


1D array with 10 elements:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into a 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into a 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# **3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [ ]:
import numpy as np

# Step 1: Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Step 2: Add a border of zeros around it to make a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("4x4 array with random float values:")
print(array_4x4)
print("\n6x6 array with a border of zeros:")
print(array_6x6)


4x4 array with random float values:
[[0.47846166 0.03413513 0.2489064  0.6506092 ]
 [0.40560561 0.62182186 0.39971004 0.10434056]
 [0.87603299 0.47386329 0.39290546 0.59638646]
 [0.72021445 0.12460527 0.96473619 0.58686777]]

6x6 array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.47846166 0.03413513 0.2489064  0.6506092  0.        ]
 [0.         0.40560561 0.62182186 0.39971004 0.10434056 0.        ]
 [0.         0.87603299 0.47386329 0.39290546 0.59638646 0.        ]
 [0.         0.72021445 0.12460527 0.96473619 0.58686777 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# **4. Using NumPy, create an array of integers from 10 to 60 with a step of 5**

In [ ]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


# **5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.**

In [ ]:
import numpy as np

# Step 1: Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Step 2: Apply different case transformations
uppercase_arr = np.char.upper(arr)   # Convert to uppercase
lowercase_arr = np.char.lower(arr)   # Convert to lowercase
titlecase_arr = np.char.title(arr)   # Convert to title case
capitalize_arr = np.char.capitalize(arr)  # Capitalize first letter only

# Step 3: Print the results
print("Original array:", arr)
print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Title case:", titlecase_arr)
print("Capitalize:", capitalize_arr)


Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


# **6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [ ]:
import numpy as np

# Step 1: Create a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Step 2: Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

# Step 3: Print the result
print("Original words:", words)
print("Words with spaces between characters:", spaced_words)


Original words: ['python' 'numpy' 'pandas']
Words with spaces between characters: ['p y t h o n' 'n u m p y' 'p a n d a s']


# **7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [ ]:
import numpy as np
# Create first NumPy array of words
arr1 = np.array([ [ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12]])


# Create 2nd NumPy array of words

arr2 = np.array([[13,14,15,16],
                 [17,18,19,20],
                 [21,22,23,24]])

# Element wise addition
addition = np.add(arr1,arr2)
print("additon :-",  addition)


# Element wise subtraction
subtraction = np.subtract(arr2,arr1)
print("subtraction :-",subtraction)


# Element wise multiplication
multiplication = np.multiply(arr1,arr2)
print("multiplication :-",multiplication)


# Element wise division
division= np.divide(arr2,arr1)
print("division :-",division)

additon :- [[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
subtraction :- [[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
multiplication :- [[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]
division :- [[13.          7.          5.          4.        ]
 [ 3.4         3.          2.71428571  2.5       ]
 [ 2.33333333  2.2         2.09090909  2.        ]]


# **8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


# **9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.**

In [ ]:
import numpy as np

# Helper function to check if a number is prime
def is_prime(num):
    if num < 2:  # Numbers less than 2 are not prime
        return False
    for i in range(2, int(num**0.5) + 1):  # Check divisors up to the square root of the number
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1000, size=100)

# Extract prime numbers from the array
prime_numbers = [num for num in random_array if is_prime(num)]

# Display results
print("Random Array:", random_array)
print("Prime Numbers:", prime_numbers)


Random Array: [982 384 776 123 762 123 208 966 568  16 948 657 414 258 311 660 746  30
  43 233 197 102 517 644 132  92  23 218 425 611 599 307 836 628 410 647
 369 528 951 956   5 909 457 243 131 191 249 503 912 956 867 192 131 744
 554 254  83 277 555  60 614 490 486 314 365  59 634 995 292 242 367 776
 776 119 988 238 659 978 473  43 157 665 877 536 818 800 706 850 600 142
 575 781  26 172 194 593 819 816 601 723]
Prime Numbers: [311, 43, 233, 197, 23, 599, 307, 647, 5, 457, 131, 191, 503, 131, 83, 277, 59, 367, 659, 43, 157, 877, 593, 601]


# **10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.**

In [ ]:
import numpy as np

# Generate a NumPy array of daily temperatures for 30 days
daily_temperatures = np.random.randint(20, 40, size=30)  # Temperatures between 20°C and 40°C

# Divide the array into weeks (4 weeks of 7 days each and 2 extra days)
weeks = daily_temperatures[:28].reshape(4, 7)  # First 28 days into 4 weeks of 7 days
remaining_days = daily_temperatures[28:]  # Last 2 days

# Calculate weekly averages
weekly_averages = np.mean(weeks, axis=1)

# Handle the remaining days
if len(remaining_days) > 0:
    remaining_average = np.mean(remaining_days)
    weekly_averages = np.append(weekly_averages, remaining_average)

# Display results
print("Daily Temperatures:", daily_temperatures)
print("Weekly Averages:", weekly_averages)


Daily Temperatures: [26 24 21 39 22 27 20 30 33 29 39 38 35 35 37 36 37 26 21 20 20 20 35 29
 26 21 27 27 30 24]
Weekly Averages: [25.57142857 34.14285714 28.14285714 26.42857143 27.        ]
